package weatherly.ui.theme

import com.example.weatherly.R

val iconMap = mapOf(
    1 to R.drawable.sunny,
    2 to R.drawable.mostly_sunny,
    3 to R.drawable.partly_sunny,
    4 to R.drawable.intermittent_clouds,
    5 to R.drawable.hazy_sunshine,
    6 to R.drawable.mostly_cloudy,
    7 to R.drawable.cloudy,
    8 to R.drawable.dreary_overcast,
    11 to R.drawable.fog,
    12 to R.drawable.showers,
    13 to R.drawable.mostly_cloudy_showers,
    14 to R.drawable.partly_sunny_showers,
    15 to R.drawable.t_storms,
    16 to R.drawable.mostly_cloudy_t_storms,
    17 to R.drawable.partly_sunny_t_storms,
    18 to R.drawable.rain,
    19 to R.drawable.flurries,
    20 to R.drawable.mostly_cloudy_flurries,
    21 to R.drawable.partly_sunny_flurries,
    22 to R.drawable.snow,
    23 to R.drawable.mostly_cloudy_snow,
    24 to R.drawable.sleet,
    25 to R.drawable.sleet,
    26 to R.drawable.freezing_rain,
    29 to R.drawable.rain_and_snow,
    30 to R.drawable.hot,
    31 to R.drawable.cold,
    32 to R.drawable.windy,
    33 to R.drawable.clear_night,
    34 to R.drawable.mostly_clear_night,
    35 to R.drawable.partly_cloudy_night,
    36 to R.drawable.intermittent_clouds_night,
    37 to R.drawable.hazy_moonlight,
    38 to R.drawable.partly_cloudy_night,
    39 to R.drawable.partly_cloudy_showers_night,
    40 to R.drawable.mostly_cloudy_showers_night,
    41 to R.drawable.partly_cloudy_t_storms_night,
    42 to R.drawable.mostly_cloudy_t_storms_night,
    43 to R.drawable.mostly_cloudy_flurries_night,
    44 to R.drawable.mostly_cloudy_snow_night
)
